apiVersion: v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  matchLabels:
    component: server
  template:
    metadata:
      label:
        component: server
    spec:
      containers:
        - name: server
          image: chenggang/multi-server
          ports:
            - containerPort: 5000
