apiVersion: v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  matchLabels:
    component: worker
  template:
    metadata:
      label:
        component: worker
    spec:
      containers:
        - name: worker
          image: chenggang/multi-worker
